# GET http://localhost:8080/api/v1/companies HTTP/1.1
# content-type: application/json

# GET http://localhost:8080/api/v1/company/2 HTTP/1.1
# content-type: application/json

# POST http://localhost:8080/api/v1/companies_all HTTP/1.1
# content-type: application/json

# [
#   {
#     "companyName": "株式会社NFTDrive",
#     "prtimesUrl": "https://prtimes.jp/main/html/rd/p/000000003.000119487.html",
#     "email": "nftdrive01@gmail.com",
#     "chargeEmployee": "中島理男",
#     "category": "アプリ",
#     "createdDate": "2023-06-25 12:16:40"
#   },
#   {
#     "companyName": "株式会社NFTDrive",
#     "prtimesUrl": "https://prtimes.jp/main/html/rd/p/000000003.000119487.html",
#     "email": "nftdrive01@gmail.com",
#     "chargeEmployee": "中島理男",
#     "category": "アプリ",
#     "createdDate": "2023-06-25 12:16:40"
#   }
# ]

# DELETE http://localhost:8080/api/v1/company/1 HTTP/1.1

# PATCH http://localhost:8080/api/v1/company/2 HTTP/1.1
# content-type: application/json

#   {
#     "companyName": "株式会社NFTDrive2"
#   }

# GET http://localhost:8080/api/v1/companies/search?email=gmail&name=合同会社 HTTP/1.1
# content-type: application/json

# GET http://localhost:8080/api/v1/companies/search/latest HTTP/1.1
# content-type: application/json

# GET http://localhost:8080/api/v1/companies/search/date?reference_date=2023-07-22 HTTP/1.1
# content-type: application/json

# GET http://localhost:8080/api/v1/companies/order_by/created_date?orderParam=asc HTTP/1.1
# content-type: application/json

# GET http://localhost:8080/api/v1/companies/prefix_search?name=株式会社 HTTP/1.1
# content-type: application/json

# POST http://localhost:8080/api/v1/companies/search HTTP/1.1
# content-type: application/json

#   {
#     "companyName": "合同会社",
#     "category": "テクノロジー"
#   }

# GET http://localhost:8080/api/v1/charge_employees/search?email=pr@dena.jp HTTP/1.1
# content-type: application/json

POST http://localhost:8080/api/v1/companies/search/by_category HTTP/1.1
content-type: application/json

  {
    "category": "テクノロジー",
    "createdDate": "2023-07-01",
    "isBeforeTime": true
  }
